[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Kung Fu"
  pageRef = "kungfu"
  weight = 20

[[main]]
  name = "Códigos"
  pageRef = "codigos"
  weight = 25

[[main]]
  name = "Sobre"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40
