colorScheme = "mcys"
defaultAppearance = "dark"
autoSwitchAppearance = true

logo = "images/logo.png"
disableTextInHeader = false

enableSearch = true
enableCodeCopy = true

mainSections = ["kungfu"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = true

[article]
  showDate = true
  showAuthor = true
  showBreadcrumbs = false
  showReadingTime = true
  showWordCount = false
  showPagination = true
  showTaxonomies = true
  showHeadingAnchors = true

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false
